[build]
builder = "nixpacks"

[build.nixpacksConfig]
phases.install = "npm install --legacy-peer-deps"

[deploy]
startCommand = "node src/index.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "3000"
